### ISSUE TITLE
导入成功，改名失败

### ISSUE THREAD

**Issue by muyan6** [ShiinaKin/Ts3AudioBotImportPlaylists#2]
最后导入显示改名失败然后音乐机器人的播放列表没有导入成功一条,请问是哪里出现了问题

**Comment by ShiinaKin** [comment]
你再确定一下参数有没有填错的，使用脚本期间不要在web操作

**Comment by muyan6** [comment]
感觉应该是没有填错的
![image](https://github.com/mashirot/Ts3AudioBotImportPlaylists/assets/45909799/bfaafc0c-8371-4a95-baf7-8cc68430a98b)

**Comment by ShiinaKin** [comment]
歌单名是否有重复，config是否有配置呢

**Comment by muyan6** [comment]
配置应该是没有问题，因为他会创建新歌单，只是里面没有歌曲
![image](https://github.com/mashirot/Ts3AudioBotImportPlaylists/assets/45909799/6dcd11ab-dac7-487d-b497-7aa7d29633e9)

**Comment by ShiinaKin** [comment]
你试试在win下使用，linux开个端口把bot的api暴露出来，或者用这个不改名的版本试试，会比较难看
[Ts3AudioBotImportPlaylists.zip](https://github.com/mashirot/Ts3AudioBotImportPlaylists/files/12565833/Ts3AudioBotImportPlaylists.zip)
