### ISSUE TITLE
好像没有办法获取会员歌曲

### ISSUE THREAD

**Issue by xixi-furry** [ShiinaKin/Ts3AudioBotImportPlaylists#3]
我看了下api上的似乎是可以获取会员歌曲的直链的，已经在api上进行了登录，看起来像是程序请求的时候没有带上cookie

**Comment by ShiinaKin** [comment]
脚本只是通过api获取歌单列表，拿到每首歌的id，然后拼接成直链，传到bot的playlist里，bot通过请求直链获取mp3，而不是bot请求api然后获取mp3
举个例子就是vip歌曲id：[394670](https://music.163.com/song?id=394670)，非vpi歌曲id：[1299289240](https://music.163.com/song?id=1299289240)
直链：https://music.163.com/song/media/outer/url?id=xxxx.mp3
你会发现 https://music.163.com/song/media/outer/url?id=1299289240.mp3 是可以下载的，
而 https://music.163.com/song/media/outer/url?id=394670.mp3 是跳转404

虽然api有提供[获取直链的接口](https://neteasecloudmusicapi.js.org/#/?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90-url)
但是这个接口返回的url会expire
